#include "compiler/src/parse_expr.bas"
#include "compiler/src/parse_datatype.bas"
#include "compiler/src/parse_dim.bas"
#include "compiler/src/parse_proc.bas"
#include "compiler/src/parse_while.bas"
#include "compiler/src/parse_if.bas"
#include "compiler/src/parse_type.bas"
#include "compiler/src/parse_enum.bas"
